name: dart_sdk_relay
description: Eppo Dart SDK Relay Server
version: 1.0.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  http: ^0.13.5
  dotenv: ^4.1.0
  path: ^1.8.3
  logging: ^1.1.1
  args: ^2.4.0

dev_dependencies:
  lints: ^2.0.1
