name: dart_sdk_relay
description: Eppo Dart SDK Relay Server
version: 1.0.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  http: ^1.3.0
  dotenv: ^4.1.0
  path: ^1.8.3
  logging: ^1.1.1
  args: ^2.4.0
  eppo_sdk:
    path: ./vendor/eppo-multiplatform/dart-sdk

dev_dependencies:
  lints: ^5.1.1
