services:
  api:
    image: Eppo-exp/test-api-server:latest
    ports:
      - "5000:5000"
    volumes:
      - ./test-data:/app/test-data:ro

  sdk:
    image: Eppo-exp/php-sdk-relay
    environment:
      - EPPO_API_SERVER=http://api:5000
      - SDK_RELAY_PORT=4000
      - SDK_RELAY_SERVER=localhost
      - SDK_REF=${SDK_REF}
    ports:
      - "4000:4000"
    depends_on:
      - api