name: Build and push Testing API

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version string for SDK Testing API release'
        required: true
        default: '1.0.0'

  push:
    paths:
      .github/workflows/*

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/build-and-push.yml
        with:
          version: 1.0.0
          docker_contex: ./package-testing/testing-api
          image_name: testing-api
