name: Build and push SDK Test Runner

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version string for SDK Test Runner release'
        required: true
        default: '1.0.0'

  push:
    paths:
      .github/workflows/*

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - uses: ./.github/workflows/build-and-push.yml
        with:
          version: ${{ inputs.version }}
          docker_contex: ./package-testing/sdk-test-runner
          image_name: sdk-test-runner
