name: Build SDK test runner

on:
  workflow_dispatch:

env:
  VERSION: 1.0.0
  TAR_NAME: sdk-test-runner-latest.tar

jobs:

  build-and-upload:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "package-testing/sdk-test-runner"

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and export
        uses: docker/build-push-action@v6
        with:
          context: ./package-testing/sdk-test-runner
          tags: Eppo-exp/sdk-test-runner:latest,Eppo-exp/sdk-test-runner:${{ env.VERSION }}
          outputs: type=docker,dest=/tmp/sdk-test-runner.tar
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sdk-test-runner-image
          path: /tmp/sdk-test-runner.tar



    # - name: Build
    #   run: |
    #     pwd
        # docker build . -t Eppo-exp/sdk-test-runner:${VERSION}
    #     docker build
    #   with:
    #     tags: Eppo-exp/sdk-test-runner:latest,Eppo-exp/sdk-test-runner:${{ env.VERSION }}
    #     outputs: type=docker,dest=/tmp/${{ env.TAR_NAME }}

    # - name: Upload artifact
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: sdk-test-runner
    #     path: /tmp/${{ env.TAR_NAME}}

# use:
#     runs-on: ubuntu-latest
#     needs: build
#     steps:
#       - name: Download artifact
#         uses: actions/download-artifact@v4
#         with:
#           name: sdk-test-runner
#           path: /tmp
        
#       - name: Load image
#         run: |
#           docker load --input /tmp/${{ env.TAR_NAME}}
#           docker image ls -a       
