name: Build and Push to Artifact Registry

on:
  workflow_dispatch:
  push:
    paths:
      .github/workflows/*

env:
  VERSION: 1.0.0
  TAR_NAME: sdk-test-runner-latest.tar

  PROJECT_ID: ${{ vars.SDK_TESTING_PROJECT_ID  }}
  REGION: ${{ vars.SDK_TESTING_REGION }}
  GAR_LOCATION: ${{ vars.SDK_TESTING_REGION }}-docker.pkg.dev/${{ vars.SDK_TESTING_PROJECT_ID  }}/sdk-testing


jobs:

  build-and-upload:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "package-testing/sdk-test-runner"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      # Set up gCloud
      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      # Allow docker access to the GAR
      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet


      # Build and push
      - name: Build and export
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./package-testing/sdk-test-runner
          tags: ${{ env.GAR_LOCATION }}/sdk-test-runner:latest


          # outputs: type=docker,dest=/tmp/sdk-test-runner.tar

      # - name: Build image
      #   run: docker build . --file DOCKERFILE_LOCATION --tag ${{ env.GAR_LOCATION }}
      #   working-directory: WORKING_DIRECTORY

      # - name: Push image
      #   run: docker push ${{ env.GAR_LOCATION }}




      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      
      # - name: Build and export
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: ./package-testing/sdk-test-runner
      #     tags: Eppo-exp/sdk-test-runner:latest,Eppo-exp/sdk-test-runner:${{ env.VERSION }}
      #     outputs: type=docker,dest=/tmp/sdk-test-runner.tar

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: sdk-test-runner-image
      #     path: /tmp/sdk-test-runner.tar



    # - name: Build
    #   run: |
    #     pwd
        # docker build . -t Eppo-exp/sdk-test-runner:${VERSION}
    #     docker build
    #   with:
    #     tags: Eppo-exp/sdk-test-runner:latest,Eppo-exp/sdk-test-runner:${{ env.VERSION }}
    #     outputs: type=docker,dest=/tmp/${{ env.TAR_NAME }}

    # - name: Upload artifact
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: sdk-test-runner
    #     path: /tmp/${{ env.TAR_NAME}}

# use:
#     runs-on: ubuntu-latest
#     needs: build
#     steps:
#       - name: Download artifact
#         uses: actions/download-artifact@v4
#         with:
#           name: sdk-test-runner
#           path: /tmp
        
#       - name: Load image
#         run: |
#           docker load --input /tmp/${{ env.TAR_NAME}}
#           docker image ls -a       
