name: Test One SDK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  
  test-php-sdk:
    runs-on: ubuntu-latest
    steps:
    - name: Echo Workflow Name
      shell: bash
      run: |
        echo "Testing eppo-exp/php-sdk"
    - name: Run remote workflow
      uses: convictional/trigger-workflow-and-wait@v1.6.1
      with:
        owner: eppo-exp
        repo: phpp-sdk
        workflow_file_name: run-tests.yml
        ref: main
        wait_interval: 10
        propagate_failure: true
        trigger_workflow: true
        wait_workflow: true
  
