name: Test SDKs
on:
  bush:
    branches:
      - main
  pull_request: #todo: remove since the SDKs won't pull the branch
    paths:
      - '**/*'

jobs:
  test-java-sdk:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up SDK with JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          repository: 'Eppo-exp/java-server-sdk'
      - name: 'Set up GCP SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
      - name: Run tests
        run: make test