name: Test SDKs

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '**/*'

jobs:
  test-java-sdk:
    runs-on: macos-latest
    steps:
      - name: Check out Java SDK
        uses: actions/checkout@v3
        with:
          repository: 'Eppo-exp/java-server-sdk'
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: 'Set up GCP SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
      - name: Run tests
        run: make test
  test-node-server-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out node server SDK'
        uses: actions/checkout@v3
        with:
          repository: 'Eppo-exp/node-server-sdk'
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          repository: 
      - uses: actions/cache@v2
        with:
          path: './node_modules'
          key: ${{ runner.os }}-root-node-modules-${{ hashFiles('./yarn.lock') }}
      - name: Install root dependencies
        run: yarn --frozen-lockfile
        working-directory: ./
      - name: 'Set up GCP SDK for downloading test data'
        uses: 'google-github-actions/setup-gcloud@v0'
      - name: Install sdk dependencies
        run: yarn --frozen-lockfile
        working-directory: ./
      - name: Run unit tests
        run: yarn test:unit
        working-directory: ./