name: Test SDKs Remotely

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  
  test-php-sdk:
    runs-on: ubuntu-latest
    steps:
    - name: Display workflow details
      shell: bash
      run: |
        echo "Testing eppo-exp/php-sdk"
    - name: Run remote workflow
      uses: convictional/trigger-workflow-and-wait@v1.6.1
      with:
        owner: Eppo-exp
        repo: php-sdk
        workflow_file_name: run-tests.yml
        ref: main
        github_token: ${{ secrets.AUTH_TOKEN }}
        wait_interval: 10
        propagate_failure: true
        trigger_workflow: true
        wait_workflow: true

  test-node-server-sdk:
    runs-on: ubuntu-latest
    steps:
    - name: Display workflow details
      shell: bash
      run: |
        echo "Testing eppo-exp/node-server-sdk"
    - name: Run remote workflow
      uses: convictional/trigger-workflow-and-wait@v1.6.1
      with:
        owner: Eppo-exp
        repo: node-server-sdk
        workflow_file_name: lint-test-sdk.yml
        ref: main
        github_token: ${{ secrets.AUTH_TOKEN }}
        wait_interval: 10
        propagate_failure: true
        trigger_workflow: true
        wait_workflow: true

  test-dotnet-sdk:
    runs-on: ubuntu-latest
    steps:
    - name: Display workflow details
      shell: bash
      run: |
        echo "Testing Eppo-exp/dot-net-server-sdk"
    - name: Run remote workflow
      uses: convictional/trigger-workflow-and-wait@v1.6.1
      with:
        owner: Eppo-exp
        repo: dot-net-server-sdk
        workflow_file_name: run-tests.yml
        ref: main
        github_token: ${{ secrets.AUTH_TOKEN }}
        wait_interval: 10
        propagate_failure: true
        trigger_workflow: true
        wait_workflow: true
      