name: Test SDKs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  
  test-php-sdk:
    runs-on: ubuntu-latest
    steps:
    - name: Check out PHP SDK
      uses: actions/checkout@v3
      with:
          repository: 'Eppo-exp/php-sdk'
          path: php-sdk
    - name: Run test workflow
      uses: ./php-sdk/.github/workflows/run-tests.yml      
  
