name: Test SDKs Locally

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
  
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  
  test-php-sdk:
    uses: Eppo-exp/php-sdk/.github/workflows/run-tests.yml@tp/workflows/remote
    with:
      test_data_branch: ${{ BRANCH_NAME}}