name: Test SDKs Remotely

on:
  push:
    branches:
      - main
    paths:
      - 'ufc/**'
  workflow_dispatch:

jobs:

  test-sdks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk:
          - { repo: "android-sdk", workflow: "test.yaml", ref: "main" }
          - { repo: "dot-net-server-sdk", workflow: "run-tests.yml", ref: "main" }
          - { repo: "eppo-ios-sdk", workflow: "unit-tests.yml", ref: "main" }
          - { repo: "golang-sdk", workflow: "test.yml", ref: "main" }
          - { repo: "java-server-sdk", workflow: "lint-test-sdk.yml", ref: "main" }
          - { repo: "js-client-sdk", workflow: "lint-test-sdk.yml", ref: "main" }
          - { repo: "node-server-sdk", workflow: "lint-test-sdk.yml", ref: "main" }
          - { repo: "php-sdk", workflow: "run-tests.yml", ref: "main" }
          - { repo: "python-sdk", workflow: "lint-test-sdk.yml", ref: "main" }
          - { repo: "react-native-sdk", workflow: "ci.yml", ref: "main" }
    steps:
    - name: Display workflow details
      shell: bash
      run: |
        echo "Testing eppo-exp/${{ matrix.sdk.repo }}"
    - name: Run remote workflow
      uses: convictional/trigger-workflow-and-wait@v1.6.1
      with:
        owner: Eppo-exp
        repo: ${{ matrix.sdk.repo }}
        workflow_file_name: ${{ matrix.sdk.workflow }}
        ref: ${{ matrix.sdk.ref }}
        github_token: ${{ secrets.AUTH_TOKEN }}
        wait_interval: 10
        propagate_failure: true
        trigger_workflow: true
        wait_workflow: true
