name: Test SDKs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  
  test-php-sdk:
    runs-on: ubuntu-latest
    steps:
    - name: Echo Workflow Name
      shell: bash
      run: |
        echo "Testing eppo-exp/php-sdk"
    - name: Run remote workflow
      uses: Eppo-exp/php-sdk/.github/workflows/run-tests.yml@tp/actions
